SELECT T.*, ROWID FROM DBCORE.DCPARAMETER T WHERE T.PARAMETERCODE LIKE '%SmartLDAP%';
SELECT T.*, ROWID FROM DBCORE.DCUSER T;
SELECT * FROM DBCORE.DCUSEREVENTLOG ORDER BY 1 DESC;

INSERT INTO DBCORE.DCUSER (IDDCUSER, USERNAME, ISINSIDER, DESCRIPTION, IDDCUSERAUTHTYPE, PASSWORDCRYPTOGRAM, RETRIESLEFT, USERNAME_DB, IDDCLANGUAGE, ISACTIVE, INACTIVITYREASON, EMAILPASSWORDRECOVERY, SECURITYCODE)
SELECT DBCORE.SIDDCUSER.NEXTVAL, 'TESTUSER' || LPAD(TO_CHAR(R), 2, '0'), -1, NULL, 'S', NULL, 9, NULL, 'UK', -1, NULL, NULL, NULL
FROM (SELECT ROWNUM AS R FROM DBA_OBJECTS WHERE ROWNUM <= 50);

INSERT INTO DBCORE.DCUSERROLE (IDDCROLE, IDDCUSER)
SELECT IDDCROLE, IDDCUSER FROM DBCORE.DCROLE R, DBCORE.DCUSER U WHERE NOT EXISTS (SELECT 'X' FROM DBCORE.DCUSERROLE UR WHERE UR.IDDCROLE = R.IDDCROLE AND UR.IDDCUSER = U.IDDCUSER) AND U.USERNAME LIKE 'TESTUSER%';

INSERT INTO DBCORE.DCUSERATTRIBUTEVALUE (IDDCUSERATTRIBUTE, IDDCUSER, USERATTRIBUTEVALUE)
SELECT IDDCUSERATTRIBUTE, IDDCUSER, 'EU' AS USERATTRIBUTEVALUE
	FROM DBCORE.DCUSER U, DBCORE.DCUSERATTRIBUTE A
		WHERE A.USERATTRIBUTENAME = 'NMI' AND NOT EXISTS (SELECT 'X' FROM DBCORE.DCUSERATTRIBUTEVALUE UA WHERE UA.IDDCUSER = U.IDDCUSER AND UA.IDDCUSERATTRIBUTE = A.IDDCUSERATTRIBUTE) AND U.USERNAME LIKE 'BEF%';

INSERT INTO DBCORE.DCUSERATTRIBUTEVALUE (IDDCUSERATTRIBUTE, IDDCUSER, USERATTRIBUTEVALUE)
SELECT IDDCUSERATTRIBUTE, IDDCUSER, '0' AS USERATTRIBUTEVALUE
	FROM DBCORE.DCUSER U, DBCORE.DCUSERATTRIBUTE A
		WHERE A.USERATTRIBUTENAME LIKE '%IDVSPrivateDB%' AND NOT EXISTS (SELECT 'X' FROM DBCORE.DCUSERATTRIBUTEVALUE UA WHERE UA.IDDCUSER = U.IDDCUSER AND UA.IDDCUSERATTRIBUTE = A.IDDCUSERATTRIBUTE) AND U.USERNAME LIKE 'BEF%';

COMMIT;
